import type { ProductMaster } from './types'

const createdAt = '2026-07-28T00:00:00.000Z'

const sku = (productId: string, index: number, optionName: string, regularPrice: number, groupBuyPrice: number, supplyPrice: number, representative = false) => ({
  id: `${productId}-sku-${index}`, skuCode: `TEST-SKU-${productId.slice(-3)}-${index}`, productId, optionName,
  regularPrice, groupBuyPrice, supplyPrice, stockStatus: 'available' as const, sellerPortalVisible: true,
  representative, active: true, createdAt, updatedAt: createdAt,
})

export const mockProductMasters: ProductMaster[] = [
  {
    id: 'product-test-001', productCode: 'TEST-PRD-001', brandId: 'brand-test-living', brandName: '[TEST] 리빙랩',
    vendorId: 'vendor-test-home', vendorName: '[TEST] 홈앤코', productName: '[TEST] 올인원 밀폐용기 세트', category: '주방', regularPrice: 69000, salePrice: 39900,
    supplyPrice: 25500, shippingFee: 0, freeShippingThreshold: 0, totalCommissionRate: 25,
    sellerCommissionRate: 17, companyCommissionRate: 8, defaultSalesChannelType: 'wise_shop_link',
    wiseShopAvailable: true, sellerCheckoutAvailable: true, brandPgSupportAvailable: true, brandPgSupportRate: 4,
    courierName: 'CJ대한통운', jejuExtraFee: 3000, islandExtraFee: 5000, bundleShippingAvailable: true,
    orderDeadlineTime: '14:00', sampleSupportType: '지원 가능', sampleAvailable: true, active: true, testData: true,
    representativeImageUrl: 'https://images.unsplash.com/photo-1584634731339-252c581abfc5?auto=format&fit=crop&w=900&q=80',
    sellerDescription: '깔끔한 수납과 보관을 돕는 실용적인 밀폐용기 구성입니다.', sellerPortalVisible: true,
    sellerPortalStatus: 'available', badges: ['new', 'recommended'], managerName: '김병희', managerContact: '카카오톡 또는 전화 문의',
    skus: [sku('product-test-001', 1, '6종 기본 세트', 69000, 39900, 25500, true), sku('product-test-001', 2, '10종 패밀리 세트', 99000, 57900, 37000)],
    memo: 'TEST 개발용 상품', createdAt, updatedAt: createdAt, version: 1,
  },
  {
    id: 'product-test-002', productCode: 'TEST-PRD-002', brandId: 'brand-test-beauty', brandName: '[TEST] 클리어뷰티',
    vendorId: 'vendor-test-beauty', vendorName: '[TEST] 뷰티파트너스', productName: '[TEST] 수분 크림 듀오', category: '뷰티', regularPrice: 72000, salePrice: 45900,
    supplyPrice: 29000, shippingFee: 3000, freeShippingThreshold: 50000, totalCommissionRate: 27,
    sellerCommissionRate: 18, companyCommissionRate: 9, defaultSalesChannelType: 'wise_shop_link',
    wiseShopAvailable: true, sellerCheckoutAvailable: false, brandPgSupportAvailable: false,
    courierName: '한진택배', jejuExtraFee: 3000, islandExtraFee: 5000, bundleShippingAvailable: false,
    orderDeadlineTime: '12:00', sampleSupportType: '협의 필요', sampleAvailable: false, active: true, testData: true,
    representativeImageUrl: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=900&q=80',
    sellerDescription: '데일리 보습 루틴에 활용하기 좋은 수분 크림 세트입니다.', sellerPortalVisible: true,
    sellerPortalStatus: 'available', badges: ['popular'], managerName: '김병희', skus: [sku('product-test-002', 1, '50ml × 2개', 72000, 45900, 29000, true)],
    memo: 'TEST 개발용 상품', createdAt, updatedAt: createdAt, version: 1,
  },
  {
    id: 'product-test-003', productCode: 'TEST-PRD-003', brandId: 'brand-test-food', brandName: '[TEST] 데일리푸드',
    vendorId: 'vendor-test-food', vendorName: '[TEST] 푸드웍스', productName: '[TEST] 단백질 쉐이크 14팩', category: '식품', regularPrice: 48000, salePrice: 34900,
    supplyPrice: 21000, shippingFee: 3000, totalCommissionRate: 24, sellerCommissionRate: 16,
    companyCommissionRate: 8, defaultSalesChannelType: 'supplier_link', wiseShopAvailable: false,
    sellerCheckoutAvailable: false, brandPgSupportAvailable: false, courierName: '롯데택배',
    jejuExtraFee: 3000, islandExtraFee: 5000, bundleShippingAvailable: true, orderDeadlineTime: '11:00',
    sampleSupportType: '지원 불가', sampleAvailable: false, active: true, testData: true, memo: 'TEST 개발용 상품',
    representativeImageUrl: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&w=900&q=80',
    sellerDescription: '간편하게 섭취할 수 있는 고단백 쉐이크 14팩 구성입니다.', sellerPortalVisible: true,
    sellerPortalStatus: 'coming_soon', badges: ['recommended'], managerName: '서주희', skus: [sku('product-test-003', 1, '초코 14팩', 48000, 34900, 21000, true)],
    createdAt, updatedAt: createdAt, version: 1,
  },
  {
    id: 'product-test-004', productCode: 'TEST-PRD-004', vendorId: 'vendor-test-life', vendorName: '[TEST] 라이프유통',
    brandId: 'brand-test-life', brandName: '[TEST] 홈데이', productName: '[TEST] 프리미엄 타월 세트', category: '생활',
    regularPrice: 56000, salePrice: 36900, supplyPrice: 23000, shippingFee: 3000, totalCommissionRate: 24,
    sellerCommissionRate: 16, companyCommissionRate: 8, defaultSalesChannelType: 'supplier_link',
    wiseShopAvailable: true, sellerCheckoutAvailable: false, brandPgSupportAvailable: false, courierName: 'CJ대한통운',
    sampleSupportType: '지원 가능', sampleAvailable: true, active: true, testData: true, sellerPortalVisible: true,
    sellerPortalStatus: 'paused', badges: ['recently_successful'], sellerDescription: '도톰한 중량과 부드러운 촉감의 타월 구성입니다.',
    representativeImageUrl: 'https://images.unsplash.com/photo-1583845112203-29329902332e?auto=format&fit=crop&w=900&q=80',
    managerName: '고정원', skus: [sku('product-test-004', 1, '화이트 5장', 56000, 36900, 23000, true)],
    createdAt, updatedAt: createdAt, version: 1,
  },
  {
    id: 'product-test-005', productCode: 'TEST-PRD-005', vendorId: 'vendor-test-secret', vendorName: '[TEST] 내부공급사',
    brandId: 'brand-test-secret', brandName: '[TEST] 준비브랜드', productName: '[TEST] 비공개 준비 상품', category: '생활',
    regularPrice: 39000, salePrice: 27900, supplyPrice: 18000, shippingFee: 3000, totalCommissionRate: 23,
    sellerCommissionRate: 15, companyCommissionRate: 8, defaultSalesChannelType: 'supplier_link',
    wiseShopAvailable: false, sellerCheckoutAvailable: false, brandPgSupportAvailable: false,
    sampleSupportType: '협의 필요', sampleAvailable: false, active: true, testData: true, sellerPortalVisible: false,
    sellerPortalStatus: 'closed', badges: [], sellerDescription: '셀러에게 노출되면 안 되는 테스트 상품입니다.',
    managerName: '김병희', skus: [sku('product-test-005', 1, '기본 옵션', 39000, 27900, 18000, true)],
    createdAt, updatedAt: createdAt, version: 1,
  },
]
