import type { CampaignDetail } from './types'

export const campaignDetailMock: CampaignDetail = {
  id: 'SCH-001',
  campaignName: '한나 × 머즈캐리어 3차',
  sellerName: '한나',
  brandName: '머즈캐리어',
  productName: '롤링 토트백',
  options: ['블랙', '실버'],
  round: '3차',
  managerName: '허윤정',
  mdName: '유시철',
  startDate: '2026-07-13',
  endDate: '2026-07-19',
  settlementDueDate: '2026-08-16',
  linkOwner: '브랜드사',
  sellerBusinessType: '개인사업자',
  contact: '셀러·브랜드 담당자 단체 채널',
  linkReviewStatus: '링크 검수 완료',
  sampleStatus: '샘플 확인 완료',
  pendingCsCount: 3,
  salesDataStatus: '판매 데이터 대기',
  settlementStatus: '정산 시작 전',
  summary: ['체크리스트 17 / 21', '링크 검수 완료', '미처리 CS 3건', '판매 데이터 대기', '정산 시작 전'],
  checklist: [
    { id: 'cl-001', group: 'D-14', title: '샘플 발송 확인', completed: true },
    { id: 'cl-002', group: 'D-14', title: '추가 샘플 필요 여부 확인', completed: true },
    { id: 'cl-003', group: 'D-13', title: '배너 제작', completed: true },
    { id: 'cl-004', group: 'D-13', title: '판매가·옵션·구성 확인', completed: true },
    { id: 'cl-005', group: 'D-13', title: '이벤트 진행 여부 확인', completed: true },
    { id: 'cl-006', group: 'D-12', title: '판매 링크 제작', completed: true },
    { id: 'cl-007', group: 'D-12', title: '상세페이지에 배너 적용', completed: true },
    { id: 'cl-008', group: 'D-11', title: '최종 링크 전달', completed: true },
    { id: 'cl-009', group: 'D-11', title: '피드·스토리 배너 전달', completed: true },
    { id: 'cl-010', group: 'D-11', title: '링크 가격 확인', completed: true },
    { id: 'cl-011', group: 'D-10', title: 'FAQ 전달', completed: true },
    { id: 'cl-012', group: 'D-10', title: '소구 포인트 정리', completed: true },
    { id: 'cl-013', group: 'D-10', title: 'CS 주의사항 전달', completed: true },
    { id: 'cl-014', group: 'D-1', title: '최저가 확인', completed: true },
    { id: 'cl-015', group: 'D-1', title: '오픈 시간 최종 확인', completed: true },
    { id: 'cl-016', group: 'D-1', title: 'CS 링크 전달', completed: true },
    { id: 'cl-017', group: 'D-1', title: '당일 배송 마감시간 전달', completed: true },
    { id: 'cl-018', group: 'D-DAY', title: '링크 정상 오픈 확인', completed: false },
    { id: 'cl-019', group: 'D-DAY', title: '매출 전달', completed: false },
    { id: 'cl-020', group: 'D-DAY', title: '배송 이슈 확인', completed: false },
    { id: 'cl-021', group: 'D-DAY', title: '영업 종료 전 재고 확인', completed: false },
    { id: 'cl-022', group: '진행 중', title: '10시 매출 전달', completed: false },
    { id: 'cl-023', group: '진행 중', title: '17시 매출 전달', completed: false },
    { id: 'cl-024', group: '진행 중', title: '배송 이슈 확인', completed: false },
    { id: 'cl-025', group: '진행 중', title: 'CS 확인', completed: false },
    { id: 'cl-026', group: '진행 중', title: '쿠팡 가격 확인', completed: false },
    { id: 'cl-027', group: '종료 다음 날', title: '최종 매출 공유', completed: false },
    { id: 'cl-028', group: '종료 다음 날', title: '셀러에게 감사 인사', completed: false },
    { id: 'cl-029', group: '종료 다음 날', title: '정산 예정일 안내', completed: false },
    { id: 'cl-030', group: 'D+14', title: '이벤트 당첨자 선정', completed: false },
    { id: 'cl-031', group: 'D+21 ~ D+28', title: '정산서 전달', completed: false },
    { id: 'cl-032', group: 'D+21 ~ D+28', title: '증빙 확인', completed: false },
    { id: 'cl-033', group: 'D+21 ~ D+28', title: '셀러 지급 요청', completed: false },
  ],
  linkInfo: {
    linkOwner: '브랜드사',
    salesLink: 'https://example.com/murz-rolling-tote',
    externalOrderLink: 'https://example.com/order-program',
    linkRequester: '허윤정',
    requestedAt: '2026.07.01',
    receivedAt: '2026.07.08',
    reviewer: '유시철',
    deliveredToSellerAt: '2026.07.11',
    reviewChecklist: {
      판매가: true,
      옵션: true,
      배송비: true,
      '오픈 시간': true,
      '종료 시간': true,
      최저가: true,
    },
    reviewCompleted: true,
    sellerDelivered: true,
  },
  proposal: {
    id: 'PROP-001',
    title: '한나 × 머즈캐리어 롤링 토트백 제안서',
    author: '유시철',
    createdAt: '2026.06.20',
    conditions: [
      { label: '정상가', proposedValue: '29,900원', confirmedValue: '29,900원' },
      { label: '판매가', proposedValue: '19,900원', confirmedValue: '19,900원' },
      { label: '셀러 수수료율', proposedValue: '17%', confirmedValue: '17%' },
      { label: '예상/실제 수량', proposedValue: '200개', confirmedValue: '200개' },
      { label: '진행 기간', proposedValue: '5일', confirmedValue: '7일' },
      { label: '옵션', proposedValue: '블랙, 실버', confirmedValue: '블랙, 실버' },
      { label: '이벤트', proposedValue: '없음', confirmedValue: '구매완료 이벤트 있음' },
    ],
  },
  priceBanner: {
    sellerName: '한나',
    headline: '한나 PICK',
    brandName: '머즈캐리어',
    productName: '롤링 토트백',
    originalPrice: '29,900원',
    groupBuyPrice: '19,900원',
    discountRate: '33%',
    saleStartDate: '7.13',
    saleEndDate: '7.19',
    shippingText: '무료배송',
    eventText: '구매완료 이벤트',
    imageUrl: '',
    cautionText: '한정 수량으로 조기 종료될 수 있습니다.',
    backgroundColor: '#f8fafc',
    accentColor: '#2563eb',
    template: 'detail',
    status: '초안',
  },
}
