import { useState } from 'react'
import type { SampleCostOwner, SamplePaymentType, SampleRequest } from '../../../features/samples/types'
import { isCostOwnerInvalid } from '../../../features/samples/sampleUtils'
import { findCampaignByName } from '../../../shared/data/campaigns'

const empty = { campaignName: '한나 × 머즈캐리어 3차', sellerName: '한나', brandName: '머즈캐리어', productName: '롤링 토트백', optionName: '블랙', quantity: '1', requestedBy: '허윤정', managerName: '허윤정', orderManagerName: '허수정', orderMethod: '브랜드사 링크', paymentType: '유상', costOwner: '회사', sampleCost: '19900', shippingCost: '0', returnRequired: false, returnDueDate: '', memo: '' }

export function CreateSampleModal({ onClose, onCreate }: { onClose: () => void; onCreate: (sample: SampleRequest) => void }) {
  const [form, setForm] = useState(empty)
  const [error, setError] = useState('')
  const update = (key: keyof typeof empty, value: string | boolean) => setForm({ ...form, [key]: value })
  const submit = () => {
    if (isCostOwnerInvalid(form.paymentType, form.costOwner as SampleCostOwner)) return setError('유상 샘플은 비용 부담자를 미정으로 저장할 수 없습니다.')
    if (form.returnRequired && !form.returnDueDate) return setError('회수 필요 샘플은 회수 예정일이 필요합니다.')
    const campaign = findCampaignByName(form.campaignName)
    onCreate({ id: crypto.randomUUID(), campaignId: campaign?.id ?? 'SCH-001', campaignName: form.campaignName, sellerName: form.sellerName, brandName: form.brandName, productName: form.productName, optionName: form.optionName, quantity: Number(form.quantity), requestedAt: '2026-07-15', requestedBy: form.requestedBy, managerId: campaign?.managerId ?? 'u-001', managerName: form.managerName, orderManagerId: form.orderManagerName === '허수정' ? 'u-002' : form.orderManagerName === '김병희' ? 'u-005' : 'u-001', orderManagerName: form.orderManagerName, orderMethod: form.orderMethod as SampleRequest['orderMethod'], paymentType: form.paymentType as SamplePaymentType, costOwner: form.costOwner as SampleCostOwner, sampleCost: Number(form.sampleCost || 0), shippingCost: Number(form.shippingCost || 0), deliveryStatus: '발주 전', returnRequired: Boolean(form.returnRequired), returnDueDate: form.returnDueDate || undefined, settlementReflected: false, settlementAmount: form.paymentType === '유상' ? Number(form.sampleCost || 0) + Number(form.shippingCost || 0) : 0, status: '요청 접수', memo: form.memo, attachments: [], activityLogs: [{ id: crypto.randomUUID(), at: '2026.07.15 14:30', actor: form.requestedBy, action: '샘플 요청 생성', memo: form.memo }] })
  }
  return <div className="drawer-backdrop"><section className="complete-modal sample-create-modal"><h3>새 샘플 요청</h3><div className="banner-form">{Object.entries({ campaignName:'공동구매 일정', sellerName:'셀러', brandName:'브랜드', productName:'상품', optionName:'옵션', quantity:'수량', requestedBy:'요청자', managerName:'담당 매니저', orderManagerName:'발주 담당자', sampleCost:'샘플 금액', shippingCost:'배송비', returnDueDate:'회수 예정일', memo:'메모' }).map(([key,label]) => <label key={key}><span>{label}</span><input value={String(form[key as keyof typeof empty])} onChange={(e) => update(key as keyof typeof empty, e.target.value)} /></label>)}<label><span>발주 방식</span><select value={form.orderMethod} onChange={(e) => update('orderMethod', e.target.value)}>{['브랜드사 링크','발주 프로그램','카카오톡 요청','직접 구매','기타'].map((v)=><option key={v}>{v}</option>)}</select></label><label><span>유상·무상</span><select value={form.paymentType} onChange={(e)=>update('paymentType', e.target.value)}><option>유상</option><option>무상</option></select></label><label><span>비용 부담자</span><select value={form.costOwner} onChange={(e)=>update('costOwner', e.target.value)}>{['회사','셀러','브랜드사','매니저','미정'].map((v)=><option key={v}>{v}</option>)}</select></label><label className="checkbox-line"><input checked={form.returnRequired} onChange={(e)=>update('returnRequired', e.target.checked)} type="checkbox" /> 회수 필요</label></div><div className="file-placeholder">첨부 파일 placeholder</div>{error && <p className="form-error">{error}</p>}<div className="action-row"><button className="primary-button" onClick={submit} type="button">저장</button><button className="secondary-button" onClick={onClose} type="button">닫기</button></div></section></div>
}
