import { useState } from 'react'
import { blankOperations, LOAN_STATUSES, SUPPLIER_STATUSES, type SampleOperations } from '../../../features/samples/sampleProvision'
import { effectiveBurden, sampleItems, itemLoanOrder } from '../../../features/samples/sampleProvision'
import type { SampleOrder } from '../../../features/samples/sampleOrderModel'
export function SampleOperationsFields({ order, busy, onSave, reflected, sellerReflected }: { order: SampleOrder; busy: boolean; onSave: (ops: SampleOperations) => Promise<void>; reflected: boolean; sellerReflected: boolean }) {
  const [ops,setOps] = useState(() => ({ ...blankOperations(), ...order.operations }))
  const patch = <K extends keyof SampleOperations>(key:K,value:SampleOperations[K]) => setOps(v => ({ ...v,[key]:value }))
  const p = order.provision!
  const outstanding = effectiveBurden(order).shares?.seller
  const candidate = ['발주완료','배송중','수령완료'].includes(order.status) && !!order.campaignId && !!effectiveBurden(order).shares?.seller
  return <section className="sample-order-section"><h3>결제·정산·회수 관리</h3><p>제공 방식: {p.method} · {['무상 제공','대여'].includes(p.method) ? '구매 정산 대상 제외' : `결제 방식: ${p.paymentMethod} · 업체: ${ops.supplierStatus}`}</p><p>셀러 정산: {sellerReflected ? '정산 반영 완료' : ops.depositReceived ? outstanding ? '일부 입금 완료 · 잔액 정산 후보' : '즉시 입금 완료 · 정산 반영 필요 없음' : ops.offsetCompleted ? '상계 완료' : candidate ? '정산 후보' : '정산 미반영'}{p.paymentMethod === '회사 선입금' && (outstanding !== 0 || sellerReflected) && <span> · 선입금 회수: {sellerReflected || (ops.depositReceived && outstanding === 0) || ops.offsetCompleted ? '완료' : '미회수·정산 후보'}</span>}</p>
    <fieldset disabled={busy || order.status === '취소'}><div className="sample-order-fields">
      {p.paymentMethod === '셀러 즉시 입금' && <><label>입금 요청일<input type="date" value={ops.depositRequestedAt} onChange={e => patch('depositRequestedAt',e.target.value)} /></label><label>입금 예정액<input type="number" min="0" value={ops.depositExpected ?? ''} onChange={e => patch('depositExpected',e.target.value === '' ? null : Number(e.target.value))} /></label><label><input type="checkbox" disabled={reflected} checked={ops.depositReceived} onChange={e => patch('depositReceived',e.target.checked)} />입금 완료 확인</label><label>입금일<input type="date" value={ops.depositReceivedAt} onChange={e => patch('depositReceivedAt',e.target.value)} /></label><label>입금 확인자<input value={ops.depositConfirmedBy} onChange={e => patch('depositConfirmedBy',e.target.value)} /></label></>}
      {!['무상 제공','대여'].includes(p.method) && <><label><input type="checkbox" disabled={reflected} checked={ops.offsetCompleted} onChange={e => patch('offsetCompleted',e.target.checked)} />이미 상계 완료</label><label>공급사 정산상태<select value={ops.supplierStatus} onChange={e => patch('supplierStatus',e.target.value as SampleOperations['supplierStatus'])}>{SUPPLIER_STATUSES.map(v => <option key={v}>{v}</option>)}</select></label></>}
      {p.method === '대여' && <><label>대여 상태<select value={ops.loanStatus} onChange={e => patch('loanStatus',e.target.value as SampleOperations['loanStatus'])}>{LOAN_STATUSES.map(v => <option key={v}>{v}</option>)}</select></label><label>발송일<input type="date" value={ops.shippedAt} onChange={e => patch('shippedAt',e.target.value)} /></label><label>수거 예정일 · 별도 지정<input type="date" value={ops.collectionDate} onChange={e => patch('collectionDate',e.target.value)} /></label><label>배송·회수 메모<textarea value={ops.collectionMemo} onChange={e => patch('collectionMemo',e.target.value)} /></label></>}
      {p.method === '테스트 후 진행' && <><label>테스트 상태<select value={ops.testStatus} onChange={e => patch('testStatus',e.target.value as SampleOperations['testStatus'])}>{['테스트 중','진행 확정','진행 안 함'].map(v => <option key={v}>{v}</option>)}</select></label><label><input type="checkbox" checked={ops.reviewRecovery} onChange={e => patch('reviewRecovery',e.target.checked)} />회수 확인 필요</label><label><input type="checkbox" checked={ops.reviewCost} onChange={e => patch('reviewCost',e.target.checked)} />비용 정산 확인 필요</label></>}
    </div><button type="button" className="primary-button" onClick={() => void onSave(ops)}>확인한 상태 저장</button></fieldset>
    {p.method === '대여' && <fieldset disabled={busy || order.status === '취소'}><legend>SKU별 회수 관리</legend>{sampleItems(order).map(item=>{const state=itemLoanOrder({...order,operations:ops},item.itemId).operations!;const update=(v:Partial<typeof state>)=>patch('itemLoans',{...ops.itemLoans,[item.itemId]:{loanStatus:state.loanStatus,shippedAt:state.shippedAt,collectionDate:state.collectionDate,collectionMemo:state.collectionMemo,...v}});return <div className="sample-sku-row" key={item.itemId}><strong>{item.productName} · {item.optionName} · {item.quantity}개</strong><small>{item.itemId}</small><div className="sample-order-fields"><label>회수상태 · {item.optionName}<select value={state.loanStatus} onChange={e=>update({loanStatus:e.target.value as SampleOperations['loanStatus']})}>{LOAN_STATUSES.map(v=><option key={v}>{v}</option>)}</select></label><label>발송일 · {item.optionName}<input type="date" value={state.shippedAt} onChange={e=>update({shippedAt:e.target.value})} /></label><label>수거 예정일 · {item.optionName}<input type="date" value={state.collectionDate} onChange={e=>update({collectionDate:e.target.value})} /></label><label>회수 메모 · {item.optionName}<input value={state.collectionMemo} onChange={e=>update({collectionMemo:e.target.value})} /></label></div></div>})}<button type="button" className="primary-button" onClick={()=>void onSave(ops)}>SKU별 회수상태 저장</button></fieldset>}
    <section><h4>SKU별 비용·정산 추적</h4>{sampleItems(order).map(item=><p key={item.itemId}>{item.optionName} · {item.quantity}개 · {item.unitPrice === null ? '단가 확인 필요' : `${(item.unitPrice*item.quantity).toLocaleString()}원`} · {['무상 제공','대여'].includes(p.method)?'정산 제외':reflected?'정산 반영 완료':'요청 단위 정산 대기'}<small>{item.itemId}</small></p>)}<small>배송비는 요청에 한 번 포함됩니다. 비용 반영과 중복 방지는 기존 샘플 요청 기준을 유지합니다.</small></section>
    <details><summary>요청 당시 제공조건 보기</summary><p>기준일: {p.capturedAt} · 총비용 조건: 단가 {p.unitPrice ?? '미확인'}원 / 배송비 {p.shippingFee}원</p><p>{p.agreedTerms || '별도 협의 없음'} · 발주방법 {p.orderMethod || '미기록'} · 랜딩 {p.landing || '미기록'}</p>{(p.method === '조건부 제공' ? [['달성',p.achieved],['미달',p.missed]] as const : [['부담',p.burden]] as const).map(([name,b]) => <p key={name}>{name} {p.method === '조건부 제공' ? `(매출 기준 ${p.threshold}원)` : ''}: {b.mode === 'free' ? '전액 무상' : `공급사 ${b.shares.supplier} / 회사 ${b.shares.company} / 셀러 ${b.shares.seller} / 매니저 ${b.shares.manager} (${b.mode === 'percent' ? '%' : '원'})`}</p>)}</details>
  </section>
}
