import { PROVISION_METHODS, PAYMENT_METHODS, provisionTotal, type Burden, type ProvisionSnapshot } from '../../../features/samples/sampleProvision'
import type { SampleOrderDraft } from '../../../features/samples/sampleOrderModel'
const owners = { supplier: '공급사', company: '회사(와이즈)', seller: '셀러', manager: '매니저' } as const
function BurdenFields({ title, value, onChange }: { title: string; value: Burden; onChange: (value: Burden) => void }) {
  const sole = Object.entries(value.shares).find(([, n]) => n === 100)?.[0] ?? 'mixed'
  return <fieldset><legend>{title}</legend><label>부담처<select value={value.mode === 'free' ? 'free' : value.mode === 'percent' ? sole : 'mixed'} onChange={e => onChange(e.target.value === 'free' ? { mode: 'free', shares: { supplier: 0, company: 0, seller: 0, manager: 0 } } : { mode: 'percent', shares: Object.fromEntries(Object.keys(owners).map(k => [k, k === e.target.value ? 100 : 0])) as Burden['shares'] })}><option value="free">전액 무상</option>{Object.entries(owners).map(([k,v]) => <option key={k} value={k}>{v}</option>)}<option value="mixed">복합 부담</option></select></label>{value.mode !== 'free' && <><label>분담 입력 방식<select value={value.mode} onChange={e => onChange({ ...value, mode: e.target.value as Burden['mode'] })}><option value="percent">비율 · 합계 100%</option><option value="amount">금액 · 합계 총비용</option></select></label><div className="sample-order-fields">{Object.entries(owners).map(([key, text]) => <label key={key}>{text} {value.mode === 'percent' ? '%' : '원'}<input type="number" min="0" step={value.mode === 'percent' ? '0.01' : '1'} value={value.shares[key as keyof typeof owners]} onChange={e => onChange({ ...value, shares: { ...value.shares, [key]: Number(e.target.value) } })} /></label>)}</div></>}</fieldset>
}
export function SampleProvisionFields({ draft, onChange }: { draft: SampleOrderDraft; onChange: (p: ProvisionSnapshot) => void }) {
  const p = draft.provision!
  const patch = <K extends keyof ProvisionSnapshot>(key: K, value: ProvisionSnapshot[K]) => onChange({ ...p, [key]: value, capturedAt: new Date().toISOString() })
  const priced = !['무상 제공', '대여'].includes(p.method)
  return <section className="sample-order-section"><h3>샘플 제공조건 · 요청 시점 저장</h3><label>샘플 제공 방식<select value={p.method} onChange={e => patch('method', e.target.value as ProvisionSnapshot['method'])}>{PROVISION_METHODS.map(v => <option key={v}>{v}</option>)}</select></label>
    {p.method === '무상 제공' && <label>제공 주체<select value={p.provider} onChange={e => patch('provider', e.target.value)}>{['공급사','회사','기타'].map(v => <option key={v}>{v}</option>)}</select><small>비용 청구·정산 차감 없음</small></label>}
    {p.method === '대여' && <p>구매 정산과 분리합니다. 발송 이후 대여 회수 탭에서 관리합니다.</p>}
    {priced && <><div className="sample-order-fields"><label>상품 단가<input type="number" min="0" step="1" value={p.unitPrice ?? ''} onChange={e => patch('unitPrice', e.target.value === '' ? null : Number(e.target.value))} /></label><label>배송비<input type="number" min="0" step="1" value={p.shippingFee} onChange={e => patch('shippingFee', Number(e.target.value))} /></label><div>상품금액 <strong>{provisionTotal(draft) === null ? '확인 필요' : (provisionTotal(draft)! - p.shippingFee).toLocaleString()}원</strong> · 총비용 <strong>{provisionTotal(draft)?.toLocaleString() ?? '확인 필요'}원</strong></div></div>
    {p.method === '조건부 제공' ? <><label>기준 매출<input required type="number" min="0" value={p.threshold ?? ''} onChange={e => patch('threshold', e.target.value === '' ? null : Number(e.target.value))} /></label><BurdenFields title="기준 달성 시 부담" value={p.achieved} onChange={v => patch('achieved',v)} /><BurdenFields title="기준 미달 시 부담" value={p.missed} onChange={v => patch('missed',v)} /></> : <BurdenFields title="최종 부담처" value={p.burden} onChange={v => patch('burden',v)} />}
    <label>결제 방식<select value={p.paymentMethod} onChange={e => patch('paymentMethod',e.target.value as ProvisionSnapshot['paymentMethod'])}>{PAYMENT_METHODS.map(v => <option key={v}>{v}</option>)}</select></label></>}
    {['진행 시 협의','테스트 후 진행','조건부 제공'].includes(p.method) && <label>이번 요청의 적용 조건<textarea required={p.method !== '조건부 제공'} value={p.agreedTerms} onChange={e => patch('agreedTerms', e.target.value)} placeholder="진행 여부·회수·비용 조건" /></label>}
    <div className="sample-order-fields"><label>발주방법<input value={p.orderMethod} onChange={e => patch('orderMethod', e.target.value)} placeholder="예: 발주모아 / 공급사 직접 요청" /></label><label>공구 진행 시 랜딩<input value={p.landing} onChange={e => patch('landing',e.target.value)} placeholder="랜딩 방식 또는 협의 내용" /></label></div>
  </section>
}
