import type { CampaignSchedule } from './types'

export const currentManagerName = '허윤정'

export const campaignSchedules: CampaignSchedule[] = [
  {
    id: 'SCH-001',
    campaignName: '한나 × 머즈캐리어 3차',
    sellerName: '한나',
    brandName: '머즈캐리어',
    productName: '롤링 토트백',
    managerName: '허윤정',
    mdName: '유시철',
    startDate: '2026-07-13',
    endDate: '2026-07-19',
    linkOwner: '브랜드사',
    landingPageCompleted: true,
    sellerBusinessType: '개인사업자',
    pendingTaskCount: 4,
    pendingCsCount: 3,
    pendingSampleCount: 0,
    linkReviewPending: false,
    orderPending: false,
    vendorSettlementCompleted: false,
    settlementDocumentCompleted: false,
    sellerPaymentCompleted: false,
    managerPaymentCompleted: false,
    todayTask: '10시 매출 전달 및 CS 확인',
  },
  {
    id: 'SCH-002',
    campaignName: '스탠다드푸드 뼈용이×전진단',
    sellerName: '전진단',
    brandName: '스탠다드푸드',
    productName: '뼈용이 건강식',
    managerName: '허윤정',
    mdName: '정다은',
    startDate: '2026-07-12',
    endDate: '2026-07-16',
    linkOwner: '자사',
    landingPageCompleted: true,
    sellerBusinessType: '법인사업자',
    pendingTaskCount: 3,
    pendingCsCount: 5,
    pendingSampleCount: 0,
    linkReviewPending: false,
    orderPending: false,
    vendorSettlementCompleted: false,
    settlementDocumentCompleted: false,
    sellerPaymentCompleted: false,
    managerPaymentCompleted: false,
    todayTask: '판매 추이 확인 및 CS 우선 처리',
  },
  {
    id: 'SCH-003',
    campaignName: '셀러A×브랜드B',
    sellerName: '셀러A',
    brandName: '브랜드B',
    productName: '데일리 이너뷰티 세트',
    managerName: '오세린',
    mdName: '김민서',
    startDate: '2026-07-10',
    endDate: '2026-07-14',
    linkOwner: '셀러',
    landingPageCompleted: true,
    sellerBusinessType: '개인사업자',
    pendingTaskCount: 6,
    pendingCsCount: 8,
    pendingSampleCount: 0,
    linkReviewPending: false,
    orderPending: false,
    vendorSettlementCompleted: false,
    settlementDocumentCompleted: false,
    sellerPaymentCompleted: false,
    managerPaymentCompleted: false,
    todayTask: '마감 데이터 수집 및 미처리 CS 정리',
  },
  {
    id: 'SCH-004',
    campaignName: '주방용품 공동구매',
    sellerName: '키친온',
    brandName: 'Maison Cook',
    productName: '스테인리스 조리도구 세트',
    managerName: '박지훈',
    mdName: '한유리',
    startDate: '2026-07-04',
    endDate: '2026-07-09',
    linkOwner: '브랜드사',
    landingPageCompleted: true,
    sellerBusinessType: '법인사업자',
    pendingTaskCount: 5,
    pendingCsCount: 2,
    pendingSampleCount: 1,
    linkReviewPending: false,
    orderPending: false,
    vendorSettlementCompleted: false,
    settlementDocumentCompleted: false,
    sellerPaymentCompleted: false,
    managerPaymentCompleted: false,
    todayTask: '판매 데이터와 취소 건 대조',
  },
  {
    id: 'SCH-005',
    campaignName: '건강식품 공동구매',
    sellerName: '헬시윤',
    brandName: 'Fit Table',
    productName: '단백질 쉐이크',
    managerName: '허윤정',
    mdName: '정다은',
    startDate: '2026-07-02',
    endDate: '2026-07-08',
    linkOwner: '자사',
    landingPageCompleted: true,
    sellerBusinessType: '개인사업자',
    pendingTaskCount: 4,
    pendingCsCount: 1,
    pendingSampleCount: 0,
    linkReviewPending: false,
    orderPending: false,
    vendorSettlementCompleted: true,
    settlementDocumentCompleted: false,
    sellerPaymentCompleted: false,
    managerPaymentCompleted: false,
    todayTask: '정산서 생성 전 공급가 검토',
  },
  {
    id: 'SCH-006',
    campaignName: '여름 스킨케어 집중 공구',
    sellerName: '뷰티하린',
    brandName: 'Lumi Skin',
    productName: '수분 크림 세트',
    managerName: '최유진',
    mdName: '김민서',
    startDate: '2026-06-26',
    endDate: '2026-07-03',
    linkOwner: '브랜드사',
    landingPageCompleted: true,
    sellerBusinessType: '법인사업자',
    pendingTaskCount: 3,
    pendingCsCount: 0,
    pendingSampleCount: 0,
    linkReviewPending: false,
    orderPending: false,
    vendorSettlementCompleted: true,
    settlementDocumentCompleted: true,
    sellerPaymentCompleted: false,
    managerPaymentCompleted: false,
    todayTask: '셀러 지급 승인 요청',
  },
  {
    id: 'SCH-007',
    campaignName: '홈트 소도구 스타터 세트',
    sellerName: '운동하는민지',
    brandName: 'Move Lab',
    productName: '밴드·폼롤러 패키지',
    managerName: '허윤정',
    mdName: '한유리',
    startDate: '2026-06-20',
    endDate: '2026-06-26',
    linkOwner: '셀러',
    landingPageCompleted: true,
    sellerBusinessType: '개인사업자',
    pendingTaskCount: 2,
    pendingCsCount: 0,
    pendingSampleCount: 0,
    linkReviewPending: false,
    orderPending: false,
    vendorSettlementCompleted: true,
    settlementDocumentCompleted: true,
    sellerPaymentCompleted: true,
    managerPaymentCompleted: false,
    todayTask: '매니저 지급 승인 대기',
  },
  {
    id: 'SCH-008',
    campaignName: '베이비 케어 정기 공구',
    sellerName: '마미노트',
    brandName: 'Tiny Haus',
    productName: '저자극 바디워시',
    managerName: '윤태호',
    mdName: '정다은',
    startDate: '2026-06-18',
    endDate: '2026-06-23',
    linkOwner: '자사',
    landingPageCompleted: true,
    sellerBusinessType: '법인사업자',
    pendingTaskCount: 1,
    pendingCsCount: 0,
    pendingSampleCount: 0,
    linkReviewPending: false,
    orderPending: false,
    vendorSettlementCompleted: true,
    settlementDocumentCompleted: true,
    sellerPaymentCompleted: false,
    managerPaymentCompleted: true,
    todayTask: '셀러 지급 내역 확인',
  },
  {
    id: 'SCH-009',
    campaignName: '프리미엄 침구 공동구매',
    sellerName: '라이프지수',
    brandName: 'Soft Room',
    productName: '냉감 침구 세트',
    managerName: '허윤정',
    mdName: '김민서',
    startDate: '2026-06-10',
    endDate: '2026-06-16',
    linkOwner: '브랜드사',
    landingPageCompleted: true,
    sellerBusinessType: '개인사업자',
    pendingTaskCount: 0,
    pendingCsCount: 0,
    pendingSampleCount: 0,
    linkReviewPending: false,
    orderPending: false,
    vendorSettlementCompleted: true,
    settlementDocumentCompleted: true,
    sellerPaymentCompleted: true,
    managerPaymentCompleted: true,
    todayTask: '완료',
  },
  {
    id: 'SCH-010',
    campaignName: '반려동물 간식 공동구매',
    sellerName: '댕댕리뷰',
    brandName: 'Pet Better',
    productName: '동결건조 간식',
    managerName: '오세린',
    mdName: '한유리',
    startDate: '2026-07-15',
    endDate: '2026-07-21',
    linkOwner: '자사',
    landingPageCompleted: true,
    sellerBusinessType: '개인사업자',
    pendingTaskCount: 2,
    pendingCsCount: 3,
    pendingSampleCount: 0,
    linkReviewPending: false,
    orderPending: false,
    vendorSettlementCompleted: false,
    settlementDocumentCompleted: false,
    sellerPaymentCompleted: false,
    managerPaymentCompleted: false,
    todayTask: '오픈 링크 최종 확인',
  },
  {
    id: 'SCH-011',
    campaignName: '리빙 수납 박스 공동구매',
    sellerName: '정리하는수연',
    brandName: 'Neat Home',
    productName: '모듈 수납 박스',
    managerName: '박지훈',
    mdName: '정다은',
    startDate: '2026-07-22',
    endDate: '2026-07-28',
    linkOwner: '브랜드사',
    landingPageCompleted: false,
    sellerBusinessType: '법인사업자',
    pendingTaskCount: 7,
    pendingCsCount: 0,
    pendingSampleCount: 2,
    linkReviewPending: true,
    orderPending: true,
    vendorSettlementCompleted: false,
    settlementDocumentCompleted: false,
    sellerPaymentCompleted: false,
    managerPaymentCompleted: false,
    todayTask: '랜딩 페이지 소재 수급',
  },
  {
    id: 'SCH-012',
    campaignName: '가을 아우터 프리오더',
    sellerName: '옷장유나',
    brandName: 'Mode Atelier',
    productName: '트렌치 코트',
    managerName: '최유진',
    mdName: '김민서',
    linkOwner: '셀러',
    landingPageCompleted: false,
    sellerBusinessType: '개인사업자',
    pendingTaskCount: 8,
    pendingCsCount: 0,
    pendingSampleCount: 3,
    linkReviewPending: true,
    orderPending: true,
    vendorSettlementCompleted: false,
    settlementDocumentCompleted: false,
    sellerPaymentCompleted: false,
    managerPaymentCompleted: false,
    todayTask: '일정 확정 전 샘플 회수',
  },
]
